booking/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/profile/', include('customer.urls')),
    path('accounts/', include('allauth.urls')),
    path('manager/', include('manager.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('dashboard.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path

from customer import views

app_name = 'customer'

urlpatterns = [
    path('order/create/', views.OrderCreateView.as_view(), name='order_create'),
    path('', views.Dashboard.as_view(), name='dashboard')
]

dashboard/urls.py
from django.urls import path

from dashboard import views

app_name = 'dash'

urlpatterns = [
    path('services/', views.ServicesList.as_view(), name='services'),

    path('blog/<str:cat>/<slug>/', views.BlogDetail.as_view(), name='blog_detail'),
    path('blog/<slug>/', views.CategoryList.as_view(), name='category'),
    path('blog/', views.BlogList.as_view(), name='blog_list'),

    path('check/availability/room/', views.RoomAvailableView.as_view(), name='check_room'),
    path('search/<str:q>/', views.BlogSearch.as_view(), name='search'),
    path('', views.HomePage.as_view(), name='home'),
]

templates/base/base.html
{% load i18n static %}
<!DOCTYPE html>
<html>
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>{% block page_title %}{% endblock %} | Booking Room</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Template by FREEHTML5.CO" />
	<meta name="keywords" content="free html5, free template, free bootstrap, html5, css3, mobile first, responsive" />
	<meta name="author" content="FREEHTML5.CO" />

  <!-- 
	//////////////////////////////////////////////////////

	FREE HTML5 TEMPLATE 
	DESIGNED & DEVELOPED by FREEHTML5.CO
		
	Website: 		http://freehtml5.co/
	Email: 			info@freehtml5.co
	Twitter: 		http://twitter.com/fh5co
	Facebook: 		https://www.facebook.com/fh5co

	//////////////////////////////////////////////////////
	 -->

  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="favicon.ico">
	<!-- <link href='https://fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700italic,900,700,900italic' rel='stylesheet' type='text/css'> -->

	<!-- Stylesheets -->
	<!-- Dropdown Menu -->
	<link rel="stylesheet" href="{% static 'css/superfish.css' %}">

	<!-- Themify Icons -->
	<link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
	<!-- Font Awesome -->
	<link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
	<!-- Flexslider  -->
	<link rel="stylesheet" href="{% static 'css/flexslider.css' %}">

	{% block add_style %}{% endblock %}
	
	<!-- Style -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" href="{% static 'plugins/sweetalert2/sweetalert2.min.css' %}">

</head>
<body>
	<div id="fh5co-wrapper">
		<div id="fh5co-page">
			<div id="fh5co-header">
				<header id="fh5co-header-section">
					<div class="container">
						<div class="nav-header">
							<a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle"><i></i></a>
							<h1 id="fh5co-logo"><a href="{% url 'dash:home' %}">Booking Room</a></h1>
							<nav id="fh5co-menu-wrap" role="navigation">
								<ul class="sf-menu" id="fh5co-primary-menu">									
									<li>
										<a href="hotel.html" class="fh5co-sub-ddown">Hotel</a>
										<ul class="fh5co-sub-menu">
											<li><a href="#">Luxe Hotel</a></li>
											<li><a href="#">Deluxe Hotel</a></li>
											<li>
												<a href="#" class="fh5co-sub-ddown">King Hotel</a>
												<ul class="fh5co-sub-menu">
													<li><a href="#" target="_blank">Build</a></li>
													<li><a href="#" target="_blank">Work</a></li>
													<li><a href="#" target="_blank">Light</a></li>
													<li><a href="#" target="_blank">Relic</a></li>
													<li><a href="#" target="_blank">Display</a></li>
													<li><a href="#" target="_blank">Sprint</a></li>
												</ul>
											</li>
											<li><a href="#">Five Star Hotel</a></li>
										</ul>
									</li>
									<li><a href="{% url 'dash:services' %}">Services</a></li>
									<li>
										<a href="{% url 'dash:blog_list' %}">Blog</a>
										<ul class="fh5co-sub-menu">
											{% for menu in menus %}
											<li><a href="{{ menu.get_absolute_url }}">{{ menu.name }}</a></li>
											{% endfor %}
										</ul>
									</li>
									<li><a href="#">Contact</a></li>
									<li>
										{% if request.user.is_authenticated %}
										<a href="#">Dashboard</a>
										<ul class="fh5co-sub-menu">
											<li><a href="{% url 'account_logout' %}">{% trans 'Log out' %}</a></li>
											<li><a href="{% url 'customer:dashboard' %}">Profile</a></li>
										</ul>
										{% else %}
										<a href="{% url 'account_login' %}">Login</a>
										{% endif %}
									</li>
								</ul>
							</nav>
						</div>
					</div>
				</header>
			</div>
			<!-- end:fh5co-header -->
			{% block content %}{% endblock %}
			
			<footer id="footer" class="fh5co-bg-color">
				<div class="container">
					<div class="row">
						<div class="col-md-3">
							<div class="copyright">
								<p>
									<small>
										&copy; 2016 Free HTML5 Template. <br> All Rights Reserved. <br>
										Designed by <a href="http://freehtml5.co" target="_blank">FreeHTML5.co</a> <br> Demo Images: <a href="http://unsplash.com/" target="_blank">Unsplash</a>
									</small>
								</p>
							</div>
						</div>
						<div class="col-md-6">
							<div class="row">
								<div class="col-md-3">
									<h3>Company</h3>
									<ul class="link">
										<li><a href="#">About Us</a></li>
										<li><a href="#">Hotels</a></li>
										<li><a href="#">Customer Care</a></li>
										<li><a href="#">Contact Us</a></li>
									</ul>
								</div>
								
								<div class="col-md-3">
									<h3>Our Facilities</h3>
									<ul class="link">
										<li><a href="#">Resturant</a></li>
										<li><a href="#">Bars</a></li>
										<li><a href="#">Pick-up</a></li>
										<li><a href="#">Swimming Pool</a></li>
										<li><a href="#">Spa</a></li>
										<li><a href="#">Gym</a></li>
									</ul>
								</div>
								
								<div class="col-md-6">
									<h3>Subscribe</h3>
									<p>Sed cursus ut nibh in semper. Mauris varius et magna in fermentum. </p>
									<form action="#" id="form-subscribe">
										<div class="form-field">
											<input type="email" placeholder="Email Address" id="email">
											<input type="submit" id="submit" value="Send">
										</div>
									</form>
								</div>
							</div>
						</div>
						
						<div class="col-md-3">
							<ul class="social-icons">
								<li>
									<a href="#"><i class="fab fa-twitter-square"></i></a>
									<a href="#"><i class="fab fa-facebook-square"></i></a>
									<a href="#"><i class="fab fa-instagram-square"></i></a>
									<a href="#"><i class="fab fa-linkedin"></i></a>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</footer>
		</div><!-- END fh5co-page -->
	</div>
	<!-- END fh5co-wrapper -->
	<!-- Javascripts -->
	<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
	<!-- Dropdown Menu -->
	<script src="{% static 'js/hoverIntent.js' %}"></script>
	<script src="{% static 'js/superfish.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
	<!-- Counters -->
	<script src="{% static 'js/jquery.countTo.js' %}"></script>
	<script src="{% static 'js/selectFx.js' %}"></script>
	<!-- Flexslider -->
	<script src="{% static 'js/jquery.flexslider-min.js' %}"></script>
	<!-- Swal -->
	<script src="{% static 'plugins/sweetalert2/sweetalert2.min.js' %}"></script>
	<script src="{% static 'js/custom.js' %}"></script>
	{% block extrajs %}{% endblock %}

	{% if messages %}
	{% for message in messages %}
	<script>
		$(function(){
			const elemnt = document.createElement('div');
			elemnt.setAttribute('class', 'alert {{ message.tags }}');
			elemnt.innerHTML = '{{ message|capfirst }}'
			
			Swal.fire({
				title: '{{ message.tags|cut:"alert-" }}',
				html: elemnt,
				icon: '{{ message.tags|cut:"alert-" }}',
				buttonsStyling: false,
				customClass: {
					confirmButton: 'btn btn-{{ message.tags|cut:"alert-" }}',
					popup: 'alert {{ message.tags }}'
				}
			})
		});
	</script>
	{% endfor %}
	{% endif %}
</body>
</html>