booking/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/profile/', include('customer.urls')),
    path('accounts/', include('allauth.urls')),
    path('manager/', include('manager.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('dashboard.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path

from customer import views

app_name = 'customer'

urlpatterns = [
    path('order/create/', views.OrderCreateView.as_view(), name='order_create'),
    path('', views.Dashboard.as_view(), name='dashboard')
]

dashboard/urls.py
from django.urls import path

from dashboard import views

app_name = 'dash'

urlpatterns = [
    path('services/', views.ServicesList.as_view(), name='services'),

    path('blog/<str:cat>/<slug>/', views.BlogDetail.as_view(), name='blog_detail'),
    path('blog/<slug>/', views.CategoryList.as_view(), name='category'),
    path('blog/', views.BlogList.as_view(), name='blog_list'),

    path('check/availability/room/', views.RoomAvailableView.as_view(), name='check_room'),
    path('search/<str:q>/', views.BlogSearch.as_view(), name='search'),
    path('', views.HomePage.as_view(), name='home'),
]

manager/urls.py
from django.urls import path
from manager import views

app_name = 'manager'

urlpatterns = [
    path('cart/detail/', views.cart_detail, name='cart_detail'),
    path('cart/add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('cart/remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    # path('add-slot/', views.AddSlot.as_view(), name='addslot'),
    path('', views.ManagerDashboard.as_view(), name='dashboard'),
]

templates/lte/base.html
{% load i18n static jazzmin admin_urls %}
{% get_jazzmin_settings request as jazzmin_settings %}
{% get_jazzmin_ui_tweaks as jazzmin_ui %}
<!-- https://docs.djangoproject.com/en/3.2/ref/contrib/admin/ -->
<!DOCTYPE html>
<html lang="id" dir="ltr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}{{ title }}{% endblock %}</title>

  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static "plugins/fontawesome-free/css/all.min.css" %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static "plugins/overlayScrollbars/css/OverlayScrollbars.min.css" %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static "dist/css/adminlte.min.css" %}">
  <!-- Custom fixes for django -->
  <link rel="stylesheet" href="{% static "jazzmin/css/main.css" %}">
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  {% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE">{% endblock %}
  {% block extrastyle %} {% endblock %}
  {% block extrahead %} {% endblock %}
</head>
<body class="hold-transition sidebar-mini layout-fixed{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}" data-admin-utc-offset="{% now 'Z' %}">
<div class="wrapper">

  <!-- Preloader -->
  <div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__wobble" src="{% static "dist/img/AdminLTELogo.png" %}" alt="AdminLTELogo" height="60" width="60">
  </div>

  {% if not is_popup %}
  {% include 'lte/navbar.html' %}

  {% include 'lte/sidebar.html' %}
  {% endif %}
  {% block sidebar %}{% endblock %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    {% block page_content %}
    {% if not is_popup %}
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">{% block content_title %}{% endblock %}</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              {% block breadcrumbs %}
              {% endblock %}
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    {% endif %}

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <section id="content" class="content">
          {% block messages %}
            {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
              <i class="icon fa fa-check"></i>{{ message|capfirst }}
            </div>
            {% endfor %}
          {% endblock messages %}
          <div class="row">
            {% block content %}{% endblock %}
          </div>
        </section>
      </div><!--/. container-fluid -->
    </div>
    <!-- /.content -->
    {% endblock %}
  </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
  {% block footer %}
  <footer class="main-footer">
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.2.0-rc
    </div>
  </footer>
  {% endblock %}
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->
<!-- jQuery -->
<!-- <script src="{% static "admin/js/vendor/jquery/jquery.js" %}"></script> -->
<!-- Bootstrap 4 -->
<!-- <script src="{% static "vendor/bootstrap/js/bootstrap.min.js" %}"></script> -->
<!-- AdminLTE App -->
<!-- <script src="{% static "vendor/adminlte/js/adminlte.min.js" %}"></script> -->
<!-- Django customisations -->
<!-- <script src="{% static "jazzmin/js/main.js" %}"></script> -->

<!-- jQuery -->
<script src="{% static "plugins/jquery/jquery.min.js" %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static "plugins/jquery-ui/jquery-ui.min.js" %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static "plugins/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
<!-- ChartJS -->
<script src="{% static "plugins/chart.js/Chart.min.js" %}"></script>
<!-- Sparkline -->
<script src="{% static "plugins/sparklines/sparkline.js" %}"></script>
<!-- JQVMap -->
<script src="{% static "plugins/jqvmap/jquery.vmap.min.js" %}"></script>
<script src="{% static "plugins/jqvmap/maps/jquery.vmap.usa.js" %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static "plugins/jquery-knob/jquery.knob.min.js" %}"></script>
<!-- daterangepicker -->
<script src="{% static "plugins/moment/moment.min.js" %}"></script>
<script src="{% static "plugins/daterangepicker/daterangepicker.js" %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static "plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js" %}"></script>
<!-- Summernote -->
<script src="{% static "plugins/summernote/summernote-bs4.min.js" %}"></script>
<!-- overlayScrollbars -->
<script src="{% static "plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js" %}"></script>
<!-- AdminLTE App -->
<script src="{% static "dist/js/adminlte.js" %}"></script>

<!-- PAGE PLUGINS -->
<!-- jQuery Mapael -->
<script src="{% static "plugins/jquery-mousewheel/jquery.mousewheel.js" %}"></script>
<script src="{% static "plugins/raphael/raphael.min.js" %}"></script>
<script src="{% static "plugins/jquery-mapael/jquery.mapael.min.js" %}"></script>
<script src="{% static "plugins/jquery-mapael/maps/usa_states.min.js" %}"></script>
<!-- ChartJS -->
<script src="{% static "plugins/chart.js/Chart.min.js" %}"></script>

{% block extrajs %}{% endblock %}
</body>
</html>

templates/lte/navbar.html
{% load i18n static %}
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-dark">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'dash:home' %}" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>

      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{% static "dist/img/user1-128x128.jpg" %}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{% static "dist/img/user8-128x128.jpg" %}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{% static "dist/img/user3-128x128.jpg" %}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link btn" data-toggle="dropdown" href="#" title="{{ request.user }}">
            <i class="far fa-user pr-2" aria-hidden="true"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-left" id="jazzy-usermenu">
            <span class="dropdown-header">{% trans 'Account' %}</span>
            <div class="dropdown-divider"></div>
            <a href="{% url 'admin:password_change' %}" class="dropdown-item">
                <i class="fas fa-key mr-2"></i> {% trans 'Change password' %}
            </a>
            <div class="dropdown-divider"></div>
            <a href="{% url 'account_logout' %}" class="dropdown-item">
                <i class="fas fa-users mr-2"></i> {% trans 'Log out' %}
            </a>
        </div>
    </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>
  {% block nav-global %}{% endblock %}
  <!-- /.navbar -->

templates/lte/sidebar.html
{% load i18n static jazzmin admin_urls %}
{% get_jazzmin_settings request as jazzmin_settings %}
{% get_side_menu as side_menu_list %}
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{% url 'manager:dashboard' %}" class="brand-link">
      <img src="{% static "dist/img/AdminLTELogo.png" %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          {% if jazzmin_settings.user_avatar %}
          <img src="{% get_user_avatar request.user %}" width="160px" class="img-circle elevation-2" alt="User Image">
          {% else %}
          <i class="fas fa-inverse user-profile fa-user-circle"></i>
          {% endif %}
        </div>
        <div class="info">
          <a href="#" class="d-block">{{ request.user }}</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item">            
            <a href="{% url 'customer:dashboard' %}" class="nav-link">            
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard
              </p>
            </a>
          </li>
          {% if request.user.is_staff %}
          <li class="nav-item">
            <a href="#" class="nav-link">
              <p>DASHBOARD<i class="fas fa-angle-left right"></i></p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'admin:dashboard_featured_changelist' %}" class="nav-link">
                  <i class="nav-icon far fa-circle text-danger"></i>
                  <p class="text">Keunggulan</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'admin:dashboard_blog_changelist' %}" class="nav-link">
                  <i class="nav-icon far fa-circle text-warning"></i>
                  <p>Blog Content</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'admin:dashboard_facilities_changelist' %}" class="nav-link">
                  <i class="nav-icon far fa-circle text-info"></i>
                  <p>Informational</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'admin:dashboard_services_changelist' %}" class="nav-link">
                  <i class="nav-icon far fa-circle text-info"></i>
                  <p>Services</p>
                </a>
              </li>
            </ul>
          </li>

          <li class="nav-header">MANAGER</li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-hotel"></i>
              <p>Rooms<i class="fas fa-angle-left right"></i></p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'admin:manager_roomtypes_changelist' %}" class="nav-link">
                  <i class="nav-icon fas fa-door-open"></i>
                  <p>Room Type</p>
                </a>
                <a href="{% url 'admin:manager_availablerooms_changelist' %}" class="nav-link">
                  <i class="nav-icon fas fa-hourglass-start"></i>
                  <p>Available Room</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-user-tie"></i>
              <p>Customers<i class="fas fa-angle-left right"></i></p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'admin:customer_roombooking_changelist' %}" class="nav-link">
                  <i class="nav-icon fas fa-user-check"></i>
                  <p>Booking</p>
                </a>
              </li>
            </ul>
          </li>
          
          <li class="nav-header">USER & GROUP</li>
          <li class="nav-item">
            <a href="{% url 'admin:auth_user_changelist' %}" class="nav-link">
              <i class="nav-icon fas fa-users"></i>
              <p>Users</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'admin:auth_group_changelist' %}" class="nav-link">
              <i class="nav-icon far fa-object-group"></i>
              <p>Group</p>
            </a>
          </li>
                    
                   
          {% endif %}
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>