booking/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/profile/', include('customer.urls')),
    path('accounts/', include('allauth.urls')),
    path('manager/', include('manager.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('dashboard.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path

from dashboard import views

app_name = 'dash'

urlpatterns = [
    path('services/', views.ServicesList.as_view(), name='services'),

    path('blog/<str:cat>/<slug>/', views.BlogDetail.as_view(), name='blog_detail'),
    path('blog/<slug>/', views.CategoryList.as_view(), name='category'),
    path('blog/', views.BlogList.as_view(), name='blog_list'),

    path('check/availability/room/', views.RoomAvailableView.as_view(), name='check_room'),
    path('search/<str:q>/', views.BlogSearch.as_view(), name='search'),
    path('', views.HomePage.as_view(), name='home'),
]

dashboard/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse, reverse_lazy
from django.utils.html import strip_tags
from django.utils.text import slugify, Truncator
from manager.models import RoomTypes
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

class AboutUs(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    image = models.ImageField(upload_to='dashboard/')

    def __str__(self):
        return self.title

class ContactUs(models.Model):
    full_name = models.CharField(max_length=50)
    email = models.EmailField()
    phone_number = models.CharField(max_length=20)
    message = models.TextField()

    def __str__(self):
        return self.full_name

class Featured(models.Model):
    name = models.OneToOneField(RoomTypes, on_delete=models.CASCADE, related_name='featured')
    desc = models.TextField()

class Facilities(models.Model):
    name = models.CharField(max_length=100, unique=True)
    icon = models.CharField(max_length=150, help_text='User font awesome icon, eg. fas fa-chalkboard')
    desc = RichTextField(verbose_name="Description")
    img = models.ImageField(upload_to="facilities/", verbose_name="Image")
    start_hour = models.TimeField(help_text="Start service hours")
    end_hour = models.TimeField(help_text="End service hours")
    
    def __str__(self):
        return self.name

class BlogCategories(models.Model):
    name = models.CharField(max_length=50, unique=True)
    desc = models.TextField()
    slug = models.SlugField(blank=True, null=True, unique=True)
    visible_menu = models.BooleanField(default=True)

    class Meta:
        ordering = ['-name']

    def save(self):
        if self.slug == None:
            self.slug = slugify(self.name)
        super(BlogCategories, self).save()
    
    def __str__(self):
        return self.slug
    
    def get_absolute_url(self):
        return reverse('dash:category', kwargs={'slug': self.slug})

def blog_image(instance, filename):
    return "blog/{0}/{1}".format(instance.category, filename)

class Blog(models.Model):
    title = models.CharField(max_length=180, unique=True)
    summary = models.TextField(blank=True, null=True)
    body = RichTextUploadingField()
    image = models.ImageField(upload_to=blog_image)
    category = models.ForeignKey(
        BlogCategories,
        to_field='slug',
        on_delete=models.PROTECT,
        related_name='blog_category'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='user_blog'
    )
    created_at = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    slug = models.SlugField(blank=True, null=True, unique=True)

    class Meta:
        ordering = ['-created_at']
    
    def strip_body(self):
        bory = strip_tags(self.body)
        trucn_bory = Truncator(bory).chars(170)
        return trucn_bory
    
    def save(self, *args, **kwargs):
        if self.slug == None:
            self.slug = slugify(self.title)
        self.summary = self.strip_body()
        super(Blog, self).save(*args, **kwargs)
    
    def get_image(self):
        if self.image:
            return self.image.url
    
    def get_absolute_url(self):
        return reverse_lazy('dash:blog_detail', kwargs={'cat': self.category, 'slug': self.slug})
    
    def __str__(self):
        return "{0} by {1}".format(self.title, self.author)

class Services(models.Model):
    icon = models.CharField(
        max_length=50,
        help_text='''icon name only. e.g: ti-alarm-clock <br> more icon : <a href="https://themify.me/themify-icons" target="_blank" rel="noopener">themify icons</a>'''
    )
    service = models.CharField(max_length=50)
    desc = models.TextField()

    def __str__(self):
        return self.service

dashboard/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from .models import Facilities, Blog

class FacilitiesForm(ModelForm):
    class Meta:
        model = Facilities
        fields = '__all__'

    def clean_img(self):
        image = self.cleaned_data.get('img', False)
        if image:
            big = float(image.size / 1024000)
            if image.size > 1*1024*1024:
                raise ValidationError("Max file size is 1MB, your image %.2f MB" % big)
            return image
        else:
            raise ValidationError("please select image!")

class BlogForm(ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'summary', 'body', 'image', 'category']
    
    def clean_image(self):
        image = self.cleaned_data.get('image', False)
        if image:
            big = float(image.size / 1024000)
            if image.size > 1*1024*1024:
                raise ValidationError("Max file size is 1MB, your image %.2f MB" % big)
            return image
        else:
            raise ValidationError("please select image!")

dashboard/views.py
from datetime import date, datetime, timedelta
from django.utils.safestring import mark_safe
from django.views.generic import DetailView, ListView, TemplateView

from dashboard.models import (
    AboutUs, Blog, BlogCategories,
    ContactUs, Facilities, Services
)
from manager.models import AvailableRooms, RoomTypes

class HomePage(TemplateView):
    template_name = 'dashboard/home.html'

    def get_context_data(self, **kwargs):
        context = super(HomePage, self).get_context_data(**kwargs)

        room_type = RoomTypes.objects.defer().all()[:3]
        context['room_type'] = room_type

        facility = Facilities.objects.all()
        context['facility'] = facility

        blog = Blog.objects.all()[:3]
        context['our_blog'] = blog
        return context

class RoomAvailableView(TemplateView):
    template_name = 'dashboard/cart/check_availability.html'

    def get_date(self, req_day: date) -> date:
        if req_day:
            year, month = (int(x) for x in req_day.split('-'))
            return date(year, month, day=1)
        return datetime.today()
    
    def next_month(self, obj):
        import calendar
        day_in_month = calendar.monthrange(obj.year, obj.month)[1]
        last = obj.replace(day=day_in_month)
        next_month = last + timedelta(days=1)
        month = str(next_month.year) + '-' + str(next_month.month)
        return month
    
    def prev_month(self, obj):
        first = obj.replace(day=1)
        prev_month = first - timedelta(days=1)
        month = str(prev_month.year) + '-' + str(prev_month.month)
        return month

    def get_context_data(self, *args, **kwargs):
        from manager.calendar import Calendar
        
        d = self.get_date(self.request.GET.get('month', None))
        cal = Calendar(self.request, d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)

        context = super(RoomAvailableView, self).get_context_data(*args, **kwargs)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = self.prev_month(d)
        context['next_month'] = self.next_month(d)

        return context

class CategoryList(ListView):
    template_name = 'dashboard/blog/categories.html'
    paginate_by = 8
    
    def get_queryset(self):
        self.slug = self.kwargs['slug']
        self.queryset = Blog.objects.filter(
            category=self.slug
        )
        return super().get_queryset()
    
    def get_context_data(self, *args, **kwargs):
        context = super(CategoryList, self).get_context_data(*args, **kwargs)
        context['judul'] = "Read Our Blog Category {}".format(self.slug)
        context['for_empty'] = "empty"
        return context

class BlogList(ListView):
    template_name = 'dashboard/blog/categories.html'
    model = Blog
    paginate_by = 8
    extra_context: dict = {
        "judul": "Read Our Blog",
        "for_empty": "no post yet"
    }

class BlogDetail(DetailView):
    template_name = 'dashboard/blog/blog_detail.html'
    model = Blog

    def get_context_data(self, *args, **kwargs):
        from random import sample
        context = super(BlogDetail, self).get_context_data(*args, **kwargs)
        related = self.model.objects.filter(category=self.kwargs['cat']).exclude(slug=self.kwargs['slug'])
        rand_related = sample(list(related), 3)
        context['related'] = rand_related
        return context

class BlogSearch(ListView):
    template_name = 'dashboard/blog/categories.html'
    paginate_by = 8
    
    def get_queryset(self):
        from django.db.models import Q
        self.q = self.request.GET.get('q')
        self.queryset = Blog.objects.defer().filter(
            Q(title__icontains=self.q) | Q(body__icontains=self.q)
        )
        return super().get_queryset()
    
    def get_context_data(self, *args, **kwargs):
        context = super(BlogSearch, self).get_context_data(*args, **kwargs)
        context['judul'] = "Hasil pencarian : {}".format(self.q)
        context['for_empty'] = "{} tidak ditemukan".format(self.q)
        return context

class ServicesList(ListView):
    model = Services
    template_name: str = 'dashboard/blog/services.html'
    paginate_by: int = 6
    extra_context: dict = {
        "judul": "We Offer Services"
    }

dashboard/templates/dashboard/home.html
{% extends 'base/base.html' %}
{% load my_filter %}
{% block content %}
<aside id="fh5co-hero" class="js-fullheight">
    <div class="flexslider js-fullheight">
        <ul class="slides">
            {% for room in room_type %}
            <li style="background-image: url('{{ room.image.url }}');">
                <div class="overlay-gradient"></div>
                <div class="container">
                    <div class="col-md-12 col-md-offset-0 text-center slider-text">
                        <div class="slider-text-inner js-fullheight">
                            <div class="desc">
                                <p><span>{{ room.name }}</span></p>
                                <h2>{{ room.desc }}</h2>
                                <p>
                                    <a href="#" class="btn btn-primary btn-lg">Book Now</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</aside>

<div class="wrap">
    <div class="container">
        <div class="row">
            <div id="availability">
                <div class="a-col">
                    <div class="cs-select cs-skin-border">Pilih Ruangan</div>
                </div>
                
                {% for room in room_type %}
                <div class="a-col alternate">
                    <div class="input-field">
                        <div class="text-a-col">{{ room.name }}</div>
                    </div>
                </div>
                {% endfor %}
                
                <div class="a-col action">
                    <a href="{% url 'dash:check_room' %}"><span>Check</span>Availability</a>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="fh5co-counter-section" class="fh5co-counters">
    <div class="container">
        <div class="row">
            <div class="col-md-3 text-center">
                <span class="fh5co-counter js-counter" data-from="0" data-to="20356" data-speed="5000" data-refresh-interval="50"></span>
                <span class="fh5co-counter-label">User Access</span>
            </div>
            <div class="col-md-3 text-center">
                <span class="fh5co-counter js-counter" data-from="0" data-to="15501" data-speed="5000" data-refresh-interval="50"></span>
                <span class="fh5co-counter-label">Hotels</span>
            </div>
            <div class="col-md-3 text-center">
                <span class="fh5co-counter js-counter" data-from="0" data-to="8200" data-speed="5000" data-refresh-interval="50"></span>
                <span class="fh5co-counter-label">Transactions</span>
            </div>
            <div class="col-md-3 text-center">
                <span class="fh5co-counter js-counter" data-from="0" data-to="8763" data-speed="5000" data-refresh-interval="50"></span>
                <span class="fh5co-counter-label">Rating &amp; Review</span>
            </div>
        </div>
    </div>
</div>

<div id="featured-hotel" class="fh5co-bg-color">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="section-title text-center">
                    <h2>Keunggulan</h2>
                </div>
            </div>
        </div>
        
        <div class="row">
            {% for room in room_type|slice:":1" %}
            <div class="feature-full-1col">
                <div class="image" style="background-image: url('{{ room.image.url }}');">
                    <div class="descrip text-center">
                        <p><small>For as low as</small><span>Rp. {{ room.price|my_decimal }}/night</span></p>
                    </div>
                </div>
                
                <div class="desc">
                    <h3>{{ room.name }}</h3>
                    <p>{{ room.desc }}</p>
                    <p><a href="{% url 'dash:check_room' %}" class="btn btn-primary btn-luxe-primary">Check Availability <i class="ti-angle-right"></i></a></p>
                </div>
            </div>
            {% endfor %}
            
            <div class="feature-full-2col">
                {% for room in room_type|slice:"1:" %}
                <div class="f-hotel">
                    <div class="image" style="background-image: url('{{ room.image.url }}');">
                        <div class="descrip text-center">
                            <p><small>For as low as</small><span>{{ room.price|my_decimal }}/night</span></p>
                        </div>
                    </div>
                    
                    <div class="desc">
                        <h3>{{ room.name }}</h3>
                        <p>{{ room.desc }}</p>
                        <p><a href="{% url 'dash:check_room' %}" class="btn btn-primary btn-luxe-primary">Check Availability <i class="ti-angle-right"></i></a></p>
                    </div>
                </div>
                {% endfor %}                
            </div>
        </div>
    </div>
</div>

<div id="hotel-facilities">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="section-title text-center">
                    <h2>Fasilitas Ruangan</h2>
                    <p>Semua ruangan akan mendapatkan fasilitas berikut</p>
                </div>
            </div>
        </div>
        
        <div id="tabs">
            <nav class="tabs-nav">
                {% for n in facility %}
                <a href="#" {% if forloop.first %}class="active"{% endif %} data-tab="tab{{ forloop.counter }}">
                    <i class="{{ n.icon }} fa-3x"></i>
                    <span>{{ n.name }}</span>
                </a>
                {% endfor %}
            </nav>
            
            <div class="tab-content-container">
                {% for c in facility %}
                <div class="tab-content{% if forloop.first %} active show{% endif %}" data-tab-content="tab{{ forloop.counter }}">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-6">
                                {% if c.img %}
                                <img src="{{ c.img.url }}" class="img-responsive" alt="{{ c.name }}">
                                {% endif %}
                            </div>
                            
                            <div class="col-md-6">
                                <span class="super-heading-sm">World Class</span>
                                <h3 class="heading">{{ c.name }}</h3>
                                {{ c.desc|safe }}
                                <p class="service-hour">
                                    <span>Service Hours</span>
                                    <strong>{{ c.start_hour }} AM - {{ c.end_hour }} PM</strong>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

<div id="testimonial">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="section-title text-center">
                    <h2>Happy Customer Says...</h2>
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col-md-4">
                <div class="testimony">
                    <blockquote>
                        &ldquo;If you’re looking for a top quality hotel look no further. We were upgraded free of charge to the Premium Suite, thanks so much&rdquo;
                    </blockquote>
                    <p class="author"><cite>John Doe</cite></p>
                </div>
            </div>

            <div class="col-md-4">
                <div class="testimony">
                    <blockquote>
                        &ldquo;Me and my wife had a delightful weekend get away here, the staff were so friendly and attentive. Highly Recommended&rdquo;
                    </blockquote>
                    <p class="author"><cite>Rob Smith</cite></p>
                </div>
            </div>
            
            <div class="col-md-4">
                <div class="testimony">
                    <blockquote>
                        &ldquo;If you’re looking for a top quality hotel look no further. We were upgraded free of charge to the Premium Suite, thanks so much&rdquo;
                    </blockquote>
                    <p class="author"><cite>Jane Doe</cite></p>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="fh5co-blog-section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="section-title text-center">
                    <h2>Our Blog</h2>
                </div>
            </div>
        </div>
        <div class="row">
            {% for blog in our_blog %}
            <div class="col-md-4 mb-4">
                <div class="blog-grid" style="background-image: url('{{ blog.get_image }}');">
                    <div class="date text-center">
                        <span>{{ blog.created_at|date:"d" }}</span>
                        <small>{{ blog.created_at|date:"M" }}</small>
                    </div>
                </div>
                <div class="desc">
                    <h3><a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a></h3>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}