booking/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/profile/', include('customer.urls')),
    path('accounts/', include('allauth.urls')),
    path('manager/', include('manager.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('dashboard.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path

from customer import views

app_name = 'customer'

urlpatterns = [
    path('order/create/', views.OrderCreateView.as_view(), name='order_create'),
    path('', views.Dashboard.as_view(), name='dashboard')
]

manager/urls.py
from django.urls import path
from manager import views

app_name = 'manager'

urlpatterns = [
    path('cart/detail/', views.cart_detail, name='cart_detail'),
    path('cart/add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('cart/remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    # path('add-slot/', views.AddSlot.as_view(), name='addslot'),
    path('', views.ManagerDashboard.as_view(), name='dashboard'),
]

manager/models.py
from django.db import models
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.core.management.base import BaseCommand, CommandError

from datetime import date, timedelta

class RoomTypes(models.Model):
    name = models.CharField(max_length=50)
    desc = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='banner/')

    def __str__(self):
        return self.name

# class DateAndSlot(models.Model):
#     booking_date = models.DateField()
#     rooms_type = models.ForeignKey(RoomTypes, on_delete=models.SET_NULL, blank=True, null=True)
#     rooms_add = models.BooleanField(default=False)

#     class Meta:
#         unique_together = ('booking_date', 'rooms_type')
    
#     def save(self, *args, **kwargs):
#         if self.booking_date < date.today():
#             raise ValidationError("Date must be in future")
#         super(DateAndSlot, self).save(*args, **kwargs)
    
#     def handle(self, *args, **options):
#         self.objects.filter(booking_date - timedelta(days=1)).delete()
#         self.stdout.write('Deleted object older than 10 days')
    
#     def __str__(self):
#         return "Date : {0} \n Type : {1}".format(self.booking_date, self.rooms_type)

class AvailableRooms(models.Model):
    booking_date_slot = models.DateField()
    type_available = models.ForeignKey(RoomTypes, on_delete=models.PROTECT)
    is_booked = models.BooleanField(default=False)

    class Meta:
        unique_together = ('booking_date_slot', 'type_available')
    
    def save(self, *args, **kwargs):
        if self.booking_date_slot < date.today():
            raise ValidationError("Date must be in future")
        super(AvailableRooms, self).save(*args, **kwargs)
    
    def handle(self, *args, **options):
        self.objects.filter(self.booking_date_slot - timedelta(days=1)).delete()
        self.stdout.write('Deleted object older than 10 days')

    def __str__(self):
        return "Booking Date : {0} Type : {1}".format(
            self.booking_date_slot,
            self.type_available.name
        )

# class Room(models.Model):
#     chosen_date_slot = models.ForeignKey(DateAndSlot, on_delete=models.CASCADE)
#     chosen_room_type = models.ForeignKey(RoomTypes, on_delete=models.CASCADE)
#     is_booked = models.BooleanField(default=False)

#     def __str__(self):
#         return "Date {0} Type: {1}".format(self.chosen_date_slot, self.chosen_room_type)

manager/forms.py
from datetime import datetime
from django.core.exceptions import ValidationError
from django import forms
from django.forms import ModelForm

from manager.models import AvailableRooms

# class DateSlotForm(ModelForm):
#     class Meta:
#         model = DateAndSlot
#         fields = ['booking_date', 'rooms_type']

# class AddRoomForm(ModelForm):
#     class Meta:
#         model = AvailableRooms
#         fields  = ['rooms_available']

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 2)]
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int
    )

    override = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput()
    )

manager/views.py
from datetime import date, timedelta
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.edit import CreateView, DeleteView

# from customer.models import RoomBooking
from manager.cart import Cart
from manager.forms import CartAddProductForm
from manager.models import AvailableRooms, RoomTypes

class ManagerDashboard(LoginRequiredMixin, TemplateView):
    template_name = 'manager/dashboard.html'

# class AddSlot(LoginRequiredMixin, SuccessMessageMixin, PermissionRequiredMixin, CreateView):
#     #model = DateAndSlot
#     permission_required = ['manager.add_dateandslot']
#     form_class = DateSlotForm
#     success_message = "Slot add sucessfully!"
#     success_url = reverse_lazy('manager:dashboard')
#     template_name = 'manager/manage/form.html'

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(AvailableRooms, id=product_id)
    #form = CartAddProductForm(request.POST)

    if product:
        cart.add(
            product=product
        )
        messages.add_message(request, messages.SUCCESS, 'Masuk keranjang')
    return redirect('manager:cart_detail')

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(AvailableRooms, id=product_id)
    cart.remove(product)
    messages.add_message(request, messages.WARNING, 'Product dikeluarkan dari keranjang')
    return redirect('manager:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={
                'quantity': item['quantity'],
                'override': True
            }
        )
    # coupon next -->
    return render(request, 'manager/cart/detail.html', {'cart': cart})

manager/templates/manager/cart/cart.html
<div class="widget-sidebar sidebar-search">
    <h5 class="sidebar-title">Sidebar :</h5>
    <div class="sidebar-content">
        <p>Bagian ini diisi apa ya, enaknya?</p>
    </div>
</div>

manager/templates/manager/cart/detail.html
{% extends 'base/base.html' %}
{% load static my_filter %}

{% block add_style %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.6.0/css/bootstrap.min.css" integrity="sha512-P5MgMn1jBN01asBgU0z60Qk4QxiXo86+wlFahKrsQf37c9cro517WzVSPPV1tDKzhku2iJ2FVgL67wG03SGnNA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock %}

{% block content %}
<div class="fh5co-parallax" style="background-image: url('/static/images/image-1.jpg');" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0 text-center fh5co-table">
                <div class="fh5co-intro fh5co-table-cell">
                    <h1 class="text-center">{% block page_title %}Booking{% endblock %}</h1>
                    <p>Made with love by the fine folks at <a href="http://freehtml5.co">FreeHTML5.co</a></p>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="fh5co-blog-section">
    <div class="container" id="calendar">
        <div class="row">
            <div class="col-md-8">
                <div class="row">
                    {% for item in cart %}
                    {% with product=item.product %}
                    <div class="col-sm-12 mb-4">
                        <div class="card card-primary border-dark">
                            <div class="card-header">
                                <p class="card-title">
                                    {{ forloop.counter }}.
                                    <strong>Room : {{ product.type_available.name }}</strong> ({{ item.quantity }} Hari) &nbsp;
                                    <button value="{% url 'manager:cart_remove' product.id %}" class="delete btn-danger">
                                        <i class="far fa-trash-alt"></i>
                                    </button>
                                </p>
                            </div>
                            
                            <div class="card-body">
                                <div class="row">
                                    <div class="col">
                                        <p class="alert alert-danger">
                                            Sebelum cekout Room ini masih bisa di booking oleh orang lain. <br>
                                            Room akan dihapus dari basket setelah 1 jam tidak cekout
                                        </p>
                                        <p class="alert alert-info">Silahkan lengkapi data pemesan</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6">
                                        <p class="card-text">Room : {{ product.type_available.name }}, Tanggal: {{ product.booking_date_slot }}</p>
                                        <p class="card-text">Harga : Rp. {{ item.price|my_decimal }}</p>
                                    </div>
                                    <div class="col-6">
                                        {% if product.type_available.image %}
                                        <img src="{{ product.type_available.image.url }}" class="img-thumbnail" width="250px">
                                        {% endif %}
                                    </div>
                                </div>
                            </div>

                            <div class="card-footer">
                                <strong>Sub Total : Rp. {{ item.total_price|my_decimal }}</strong>
                            </div>
                        </div>
                    </div>
                    {% endwith %}
                    {% endfor %}
                </div>

                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <p class="card-title">Ringkasan</p>
                            </div>
                            <div class="card-body">
                                <p>Total Tagihan: Rp. {{ cart.get_total_price|my_decimal }}</p>
                                <p><a href="{% url 'customer:order_create' %}">Pesan</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                {% include 'manager/cart/cart.html' %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extrajs %}
<script src="{% static 'plugins/popper/popper.min.js' %}"></script>
<script>
    $(document).ready(function(){
        window.location.hash = '#calendar';
    });
    $('.dropdown-toggle').dropdown();
    $(".delete").click(function(){
        var button=$(this).val();
        if(confirm('Yakin hapus produk ini?')){
          $.ajax({
            type:'POST',
            url:button,
            data:{'csrfmiddlewaretoken':$('input[name=csrfmiddlewaretoken]').val()},
            success:function(data){
              alert("Produk sudah dihapus dari cart");
              window.location.reload();
            }
          });
        }
      });
</script>
{% endblock %}